config/routes.rb
TimeTravel::Application.routes.draw do
  devise_for :users
  resources :friends
  resources :extras

  resources :trip_features

  resources :user_preferences

  resources :purchases

  resources :orders
  resources :hotels

  resources :trips do
    resources :hotels
  end
  resources :users

  root :to => 'home#index'
  match "trips/detail/:id" => 'home#index'
  match "admin" => 'admin#index'

  match 'index' => 'home#index'

end

app/models/trip_feature.rb
class TripFeature < ActiveRecord::Base
  belongs_to :trip
end

app/controllers/trip_features_controller.rb
class TripFeaturesController < ApplicationController
  # GET /trip_features
  # GET /trip_features.json
  def index
    @trip_features = TripFeature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trip_features }
    end
  end

  # GET /trip_features/1
  # GET /trip_features/1.json
  def show
    @trip_feature = TripFeature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip_feature }
    end
  end

  # GET /trip_features/new
  # GET /trip_features/new.json
  def new
    @trip_feature = TripFeature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip_feature }
    end
  end

  # GET /trip_features/1/edit
  def edit
    @trip_feature = TripFeature.find(params[:id])
  end

  # POST /trip_features
  # POST /trip_features.json
  def create
    @trip_feature = TripFeature.new(params[:trip_feature])

    respond_to do |format|
      if @trip_feature.save
        format.html { redirect_to @trip_feature, notice: 'Trip feature was successfully created.' }
        format.json { render json: @trip_feature, status: :created, location: @trip_feature }
      else
        format.html { render action: "new" }
        format.json { render json: @trip_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trip_features/1
  # PUT /trip_features/1.json
  def update
    @trip_feature = TripFeature.find(params[:id])

    respond_to do |format|
      if @trip_feature.update_attributes(params[:trip_feature])
        format.html { redirect_to @trip_feature, notice: 'Trip feature was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trip_features/1
  # DELETE /trip_features/1.json
  def destroy
    @trip_feature = TripFeature.find(params[:id])
    @trip_feature.destroy

    respond_to do |format|
      format.html { redirect_to trip_features_url }
      format.json { head :ok }
    end
  end
end

app/helpers/trip_features_helper.rb
module TripFeaturesHelper
end

app/views/trip_features/_form.html.erb
<%= form_for(@trip_feature) do |f| %>
  <% if @trip_feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip_feature.errors.count, "error") %> prohibited this trip_feature from being saved:</h2>

      <ul>
      <% @trip_feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trip %><br />
    <%= f.text_field :trip %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trip_features/edit.html.erb
<h1>Editing trip_feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip_feature %> |
<%= link_to 'Back', trip_features_path %>

app/views/trip_features/index.html.erb
<h1>Listing trip_features</h1>

<table>
  <tr>
    <th>Trip</th>
    <th>Kind</th>
    <th>Slug</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trip_features.each do |trip_feature| %>
  <tr>
    <td><%= trip_feature.trip %></td>
    <td><%= trip_feature.kind %></td>
    <td><%= trip_feature.slug %></td>
    <td><%= trip_feature.description %></td>
    <td><%= link_to 'Show', trip_feature %></td>
    <td><%= link_to 'Edit', edit_trip_feature_path(trip_feature) %></td>
    <td><%= link_to 'Destroy', trip_feature, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip feature', new_trip_feature_path %>

app/views/trip_features/new.html.erb
<h1>New trip_feature</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_features_path %>

app/views/trip_features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Trip:</b>
  <%= @trip_feature.trip %>
</p>

<p>
  <b>Kind:</b>
  <%= @trip_feature.kind %>
</p>

<p>
  <b>Slug:</b>
  <%= @trip_feature.slug %>
</p>

<p>
  <b>Description:</b>
  <%= @trip_feature.description %>
</p>


<%= link_to 'Edit', edit_trip_feature_path(@trip_feature) %> |
<%= link_to 'Back', trip_features_path %>