config/routes.rb
TimeTravel::Application.routes.draw do
  devise_for :users
  resources :friends
  resources :extras

  resources :trip_features

  resources :user_preferences

  resources :purchases

  resources :orders
  resources :hotels

  resources :trips do
    resources :hotels
  end
  resources :users

  root :to => 'home#index'
  match "trips/detail/:id" => 'home#index'
  match "admin" => 'admin#index'

  match 'index' => 'home#index'

end

app/models/user_preference.rb
class UserPreference < ActiveRecord::Base
  belongs_to :user
end

app/controllers/user_preferences_controller.rb
class UserPreferencesController < ApplicationController
  # GET /user_preferences
  # GET /user_preferences.json
  def index
    @user_preferences = UserPreference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_preferences }
    end
  end

  # GET /user_preferences/1
  # GET /user_preferences/1.json
  def show
    @user_preference = UserPreference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_preference }
    end
  end

  # GET /user_preferences/new
  # GET /user_preferences/new.json
  def new
    @user_preference = UserPreference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_preference }
    end
  end

  # GET /user_preferences/1/edit
  def edit
    @user_preference = UserPreference.find(params[:id])
  end

  # POST /user_preferences
  # POST /user_preferences.json
  def create
    @user_preference = UserPreference.new(params[:user_preference])

    respond_to do |format|
      if @user_preference.save
        format.html { redirect_to @user_preference, notice: 'User preference was successfully created.' }
        format.json { render json: @user_preference, status: :created, location: @user_preference }
      else
        format.html { render action: "new" }
        format.json { render json: @user_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_preferences/1
  # PUT /user_preferences/1.json
  def update
    @user_preference = UserPreference.find(params[:id])

    respond_to do |format|
      if @user_preference.update_attributes(params[:user_preference])
        format.html { redirect_to @user_preference, notice: 'User preference was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_preferences/1
  # DELETE /user_preferences/1.json
  def destroy
    @user_preference = UserPreference.find(params[:id])
    @user_preference.destroy

    respond_to do |format|
      format.html { redirect_to user_preferences_url }
      format.json { head :ok }
    end
  end
end

app/helpers/user_preferences_helper.rb
module UserPreferencesHelper
end

app/views/user_preferences/_form.html.erb
<%= form_for(@user_preference) do |f| %>
  <% if @user_preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_preference.errors.count, "error") %> prohibited this user_preference from being saved:</h2>

      <ul>
      <% @user_preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_preferences/edit.html.erb
<h1>Editing user_preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_preference %> |
<%= link_to 'Back', user_preferences_path %>

app/views/user_preferences/index.html.erb
<h1>Listing user_preferences</h1>

<table>
  <tr>
    <th>User</th>
    <th>Kind</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_preferences.each do |user_preference| %>
  <tr>
    <td><%= user_preference.user %></td>
    <td><%= user_preference.kind %></td>
    <td><%= user_preference.name %></td>
    <td><%= user_preference.description %></td>
    <td><%= link_to 'Show', user_preference %></td>
    <td><%= link_to 'Edit', edit_user_preference_path(user_preference) %></td>
    <td><%= link_to 'Destroy', user_preference, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User preference', new_user_preference_path %>

app/views/user_preferences/new.html.erb
<h1>New user_preference</h1>

<%= render 'form' %>

<%= link_to 'Back', user_preferences_path %>

app/views/user_preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_preference.user %>
</p>

<p>
  <b>Kind:</b>
  <%= @user_preference.kind %>
</p>

<p>
  <b>Name:</b>
  <%= @user_preference.name %>
</p>

<p>
  <b>Description:</b>
  <%= @user_preference.description %>
</p>


<%= link_to 'Edit', edit_user_preference_path(@user_preference) %> |
<%= link_to 'Back', user_preferences_path %>