config/routes.rb
TimeTravel::Application.routes.draw do
  devise_for :users
  resources :friends
  resources :extras

  resources :trip_features

  resources :user_preferences

  resources :purchases

  resources :orders
  resources :hotels

  resources :trips do
    resources :hotels
  end
  resources :users

  root :to => 'home#index'
  match "trips/detail/:id" => 'home#index'
  match "admin" => 'admin#index'

  match 'index' => 'home#index'

end

app/models/extra.rb
class Extra < ActiveRecord::Base
  belongs_to :trip
  attr_accessible :description, :price, :name, :trip, :orders
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  
  belongs_to :sender, :class_name => "User", :foreign_key => :request_sender_id
  belongs_to :receiver, :class_name => "User", :foreign_key => :request_receiver_id
  
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :trip
  attr_accessible :description, :price, :name, :trip, :nights_ordered
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :hotels
  has_many :extras
  attr_accessible :name, :description, :start_date, :end_date,
      :image_name, :slug, :tag_line, :price, :location, :activity, :orders
end

app/models/trip_feature.rb
class TripFeature < ActiveRecord::Base
  belongs_to :trip
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :purchases
  has_many :user_preferences 
  has_many :friend_requests, :class_name => "Friend", :foreign_key => :request_sender_id
  has_many :friend_requests_received, :class_name => "Friend", :foreign_key => :request_receiver_id
  
  def users_requesting_me
    friend_requests.map(&:receiver)
  end
  
  def users_i_am_requesting
    friend_requests_received.map(&:sender)
  end
  
  def friends
    (users_requesting_me + users_i_am_requesting).uniq
  end
  
end

app/models/user_preference.rb
class UserPreference < ActiveRecord::Base
  belongs_to :user
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
  end
end

app/controllers/extras_controller.rb
class ExtrasController < ApplicationController

  respond_to :html, :json

  def index
    @extras = Extra.where(:id => params[:ids]).all
    render :json => @extras
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  respond_to :html, :json

  def index
    @hotels = Hotel.where(:id => params[:ids]).all
    respond_to do |format|
      format.html { render text: "", layout: "home" }
      format.json { render json: @hotels }
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
    respond_to do |format|
      format.html { render text: "", layout: "home" }
      format.json { render json: @hotel }
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    render text: ""
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {trips: @trips} }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  VALUES = [0, 3, 4, 2, 5, 6]

  def rating
    @trip = Trip.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json:
        {values: VALUES, id: @trip.id}}
    end
  end

  def update_rating
    @trip = Trip.find(params[:id])
    VALUES[params[:rating].to_i] += 1
    response = {values: VALUES, id: @trip.id}
    render json: response
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all(:order => "last_name ASC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/trip_features_helper.rb
module TripFeaturesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Time Travel Adventures</title>
  <%= stylesheet_link_tag    "application" %>

  <%= javascript_include_tag "application" %>
  <%= yield :javascript %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container"><%= yield %></div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trips: <%= controller.action_name %></title>
  <%= stylesheet_link_tag    "application", :debug => true %>
  <%= javascript_include_tag :application, :debug => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h1 class="span-10">
    <%= link_to "Time Travel Adventures", root_path%>

  </h1>

  <div class="span-14 last">
    <% if current_user %>
      <div>Logged in as <%= current_user.first_name %> <%= current_user.last_name %></div>
      <div><%= link_to "Log Out", destroy_user_session_path %></div>
    <% else %>
    <div><%= link_to "Log In", new_user_session_path, :id => "log_in" %></div>
    <div><%= link_to "Sign Up", new_user_path %></div>
    <% end %>
  </div>
  <br clear="all" />
  
  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <p class="alert"><%= alert %></p>
  
  <div class="span-4">
    Things To Do:
    <br />
    <% if current_user %>
      <%= link_to "My Profile", user_path(:id => current_user) %>
      <br/>
      <%= link_to "Edit My Profile", edit_user_path(:id => current_user) %>
      <br />
      <%= link_to "Edit My Preferences", user_preferences_path %>
      <br />
      <%= link_to "Make Friends", users_path %>
    <% end %>
    <br />
    <%= link_to "More about time travel", "http://en.wikipedia.org/wiki/Time_travel" %>
  </div>

  <div class="span-20 last">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Time Travel Adventures</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= yield :javascript %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container"><%= yield %></div>
</body>
</html>